meta_title: "Syndicat de Lutte Anti Franglais - SLAF"
meta_description: "Pourquoi parler Anglais quand on peut le faire en Fran√ßais ?"
meta_image: "logo-meta.jpg" # should exist in `app/assets/images/`
twitter_account: "@slaf_fr"   # required for Twitter Cards